spring:
 datasource:
   url: jdbc:mysql://localhost:3306/employee_details?useSSL=false
   username: root
   password: **** #Enter your password here

#JPA settings
 jpa:
    hibernate:
      ddl-auto: create